version: "3.7"

services:
  docs:
    # choose appropriate version
    image: sismics/docs:travis-664
    container_name: teedy
    restart: unless-stopped
    environment:
      # edit with your server name and port
      - DOCS_BASE_URL=https://your_ip_or_domain_name:your_port
      # teedydb needs to reflect your db container service name, teedy is the name of the db
      - DATABASE_URL=jdbc:postgresql://teedydb:5432/teedy
      - DATABASE_USER=your_db_username
      - DATABASE_PASSWORD=your_db_password
      # choose your language
      - DOCS_DEFAULT_LANGUAGE=Nederlands
    volumes:
      # adjust with the correct host path for your configuration
      - /path/to/your/docker/teedy/data:/data
    ports:
      # choose an available port to be mapped on your host
      - "8100:8080"
  teedydb:
    image: postgres:13.0
    restart: unless-stopped
    container_name: teedy_db
    volumes:
      # adjust with the correct host path for your configuration
      - /path/to/your/docker/teedy/postgresdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=your_db_username
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=teedy
  docs-importer:
    # choose appropriate version
    image: sismics/docs-importer:travis-663
    container_name: teedy_importer
    restart: unless-stopped
    volumes:
      # adjust with the correct host path for your configuration
      - /path/to/your/docker/teedy/import:/import
      # adjust with the correct host path for your configuration, here lives the configuration file for the importer
      - /path/to/your/docker/teedy/config:/root/.config/preferences
